// Code generated by MockGen. DO NOT EDIT.
// Source: minikube_downloader.go

// package lib is a generated GoMock package.
package lib

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDownloader is a mock of Downloader interface.
type MockDownloader struct {
	ctrl     *gomock.Controller
	recorder *MockDownloaderMockRecorder
}

// MockDownloaderMockRecorder is the mock recorder for MockDownloader.
type MockDownloaderMockRecorder struct {
	mock *MockDownloader
}

// NewMockDownloader creates a new mock instance.
func NewMockDownloader(ctrl *gomock.Controller) *MockDownloader {
	mock := &MockDownloader{ctrl: ctrl}
	mock.recorder = &MockDownloaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloader) EXPECT() *MockDownloaderMockRecorder {
	return m.recorder
}

// ISO mocks base method.
func (m *MockDownloader) ISO(urls []string, skipChecksum bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ISO", urls, skipChecksum)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ISO indicates an expected call of ISO.
func (mr *MockDownloaderMockRecorder) ISO(urls, skipChecksum interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ISO", reflect.TypeOf((*MockDownloader)(nil).ISO), urls, skipChecksum)
}

// PreloadTarball mocks base method.
func (m *MockDownloader) PreloadTarball(k8sVersion, containerRuntime, driver string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreloadTarball", k8sVersion, containerRuntime, driver)
	ret0, _ := ret[0].(error)
	return ret0
}

// PreloadTarball indicates an expected call of PreloadTarball.
func (mr *MockDownloaderMockRecorder) PreloadTarball(k8sVersion, containerRuntime, driver interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreloadTarball", reflect.TypeOf((*MockDownloader)(nil).PreloadTarball), k8sVersion, containerRuntime, driver)
}
