// Code generated by MockGen. DO NOT EDIT.
// Source: schema_builder.go

// Package generator is a generated GoMock package.
package generator

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMinikubeBinary is a mock of MinikubeBinary interface.
type MockMinikubeBinary struct {
	ctrl     *gomock.Controller
	recorder *MockMinikubeBinaryMockRecorder
}

// MockMinikubeBinaryMockRecorder is the mock recorder for MockMinikubeBinary.
type MockMinikubeBinaryMockRecorder struct {
	mock *MockMinikubeBinary
}

// NewMockMinikubeBinary creates a new mock instance.
func NewMockMinikubeBinary(ctrl *gomock.Controller) *MockMinikubeBinary {
	mock := &MockMinikubeBinary{ctrl: ctrl}
	mock.recorder = &MockMinikubeBinaryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMinikubeBinary) EXPECT() *MockMinikubeBinaryMockRecorder {
	return m.recorder
}

// GetStartHelpText mocks base method.
func (m *MockMinikubeBinary) GetStartHelpText(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStartHelpText", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStartHelpText indicates an expected call of GetStartHelpText.
func (mr *MockMinikubeBinaryMockRecorder) GetStartHelpText(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStartHelpText", reflect.TypeOf((*MockMinikubeBinary)(nil).GetStartHelpText), ctx)
}

// GetVersion mocks base method.
func (m *MockMinikubeBinary) GetVersion(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockMinikubeBinaryMockRecorder) GetVersion(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockMinikubeBinary)(nil).GetVersion), ctx)
}
